// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe_ubuEsDK44sZBz5PnI5bCwMa5kk0WAA',
    appId: '1:998727924060:web:8e5e05adc57177a357e999',
    messagingSenderId: '998727924060',
    projectId: 'auth-32224',
    authDomain: 'auth-32224.firebaseapp.com',
    storageBucket: 'auth-32224.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0GwwJwS3l4Z4Y0AViwIrq4cP9CEfkHGE',
    appId: '1:998727924060:android:7301c8102c54646857e999',
    messagingSenderId: '998727924060',
    projectId: 'auth-32224',
    storageBucket: 'auth-32224.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv8EiLfTpVIFdg1qDq2IZdoZE-_Orlsbk',
    appId: '1:998727924060:ios:440a89a0de8551ec57e999',
    messagingSenderId: '998727924060',
    projectId: 'auth-32224',
    storageBucket: 'auth-32224.appspot.com',
    iosClientId: '998727924060-68lale54kdctp8lqmooflr65t2jtmmal.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv8EiLfTpVIFdg1qDq2IZdoZE-_Orlsbk',
    appId: '1:998727924060:ios:603c94d899bb099c57e999',
    messagingSenderId: '998727924060',
    projectId: 'auth-32224',
    storageBucket: 'auth-32224.appspot.com',
    iosClientId: '998727924060-o6t90hteph786grcr4994vqlp0r20d9e.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectx.RunnerTests',
  );
}
